name: Deploy App

on:
  workflow_dispatch:
    push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.2

      - name: Build binary
        run: |
          go mod download
          go build -o url-shortener ./

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your.server.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          scp server root@5.189.237.243:/root/apps/url-shortener
          ssh root@5.189.237.243 'pkill server || true && nohup /root/apps/url-shortener/server > server.log 2>&1 &'
