name: Deploy API Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build binary
        run: go build -o server .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 5.189.237.243 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@5.189.237.243 'mkdir -p /root/api'
          scp server root@5.189.237.243:/root/api/server
          ssh root@5.189.237.243 '
            pkill server || true
            nohup /root/api/server > /root/api/server.log 2>&1 &
          '
